### ISSUE TITLE
Would you like me to write some documentation and some additions to the sh script?

### ISSUE THREAD

**Issue by CleanMachine1** [SuperPi911/Raspberry-Pi-4-400-Stress-Test#1]

**Comment by SuperPi911** [comment]
yes

**Comment by SuperPi911** [comment]
Can you send all the modified files to update my repo?

**Comment by CleanMachine1** [comment]
They are in the PR request, all fully done

**Comment by CleanMachine1** [comment]
#2

**Comment by CleanMachine1** [comment]
@SuperPi911 Why did you not accept my PR??

**Comment by SuperPi911** [comment]
What is a PR?

**Comment by CleanMachine1** [comment]
A PR (Pull Request) is when you want to merge a fork (a clone) or a branch of the current repo, into 1 thing

If you go to the Pull Request tab on this site and click mine and accept it and merge, then I am listed as a contributor and my code is put into the main repo

**Comment by CleanMachine1** [comment]
Actually if would be good to merge since you changed one of my lines making it useless
